parameters:
#    orange_rt_anonymize.example.class: OrangeRT\AnonymizeBundle\Example

services:
#    orange_rt_anonymize.example:
#        class: %orange_rt_anonymize.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
