<?php
/******************************************************************************
 * Copyright (c) 2017.                                                        *
 ******************************************************************************/

namespace OrangeRT\AnonymizeBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class OrangeRTAnonymizeBundle extends Bundle
{
    protected function createContainerExtension()
    {
        return parent::createContainerExtension(); // TODO: Change the autogenerated stub
    }
}
